package com.ultra.type

import android.inputmethodservice.InputMethodService
import android.view.View
import android.view.inputmethod.EditorInfo
import android.widget.Button
import android.widget.LinearLayout

class UltraKeyboardService : InputMethodService() {
    
    override fun onCreateInputView(): View {
        val layout = LinearLayout(this).apply {
            orientation = LinearLayout.HORIZONTAL
            setBackgroundColor(0xFFEEEEEE.toInt())
        }

        val btnType = Button(this).apply {
            text = "Ultra Type (Auto)"
            setOnClickListener {
                simulateHumanTyping("This is a stealth message generated by UltraType.")
            }
        }

        layout.addView(btnType)
        return layout
    }

    private fun simulateHumanTyping(text: String) {
        val ic = currentInputConnection ?: return
        
        // خوارزمية الكتابة بسرعة متغيرة (محاكاة البشر)
        Thread {
            for (char in text) {
                ic.commitText(char.toString(), 1)
                Thread.sleep((50..200).random().toLong()) // تأخير عشوائي بين الضربات
            }
        }.start()
    }
}
